// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommentHotFlowVector.proto

package com.weibo.api.api_test;

public final class CommentHotFlowVectorWrap {
  private CommentHotFlowVectorWrap() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommentHotFlowVectorOrBuilder extends
          // @@protoc_insertion_point(interface_extends:CommentHotFlowVector)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta>
    getVectorList();
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getVector(int index);
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    int getVectorCount();
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    java.util.List<? extends com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder>
    getVectorOrBuilderList();
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder getVectorOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code CommentHotFlowVector}
   */
  public  static final class CommentHotFlowVector extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:CommentHotFlowVector)
          CommentHotFlowVectorOrBuilder {
    // Use CommentHotFlowVector.newBuilder() to construct.
    private CommentHotFlowVector(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommentHotFlowVector() {
      vector_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CommentHotFlowVector(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 1690: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vector_ = new java.util.ArrayList<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta>();
                mutable_bitField0_ |= 0x00000001;
              }
              vector_.add(
                      input.readMessage(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vector_ = java.util.Collections.unmodifiableList(vector_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.class, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.Builder.class);
    }

    public interface CommentHotflowMetaOrBuilder extends
            // @@protoc_insertion_point(interface_extends:CommentHotFlowVector.CommentHotflowMeta)
            com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint64 cid = 201;</code>
       */
      long getCid();

      /**
       * <code>double score = 202;</code>
       */
      double getScore();
    }
    /**
     * Protobuf type {@code CommentHotFlowVector.CommentHotflowMeta}
     */
    public  static final class CommentHotflowMeta extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:CommentHotFlowVector.CommentHotflowMeta)
            CommentHotflowMetaOrBuilder {
      // Use CommentHotflowMeta.newBuilder() to construct.
      private CommentHotflowMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CommentHotflowMeta() {
        cid_ = 0L;
        score_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private CommentHotflowMeta(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 1608: {

                cid_ = input.readUInt64();
                break;
              }
              case 1617: {

                score_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
                  e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_CommentHotflowMeta_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.class, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder.class);
      }

      public static final int CID_FIELD_NUMBER = 201;
      private long cid_;
      /**
       * <code>uint64 cid = 201;</code>
       */
      public long getCid() {
        return cid_;
      }

      public static final int SCORE_FIELD_NUMBER = 202;
      private double score_;
      /**
       * <code>double score = 202;</code>
       */
      public double getScore() {
        return score_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        if (cid_ != 0L) {
          output.writeUInt64(201, cid_);
        }
        if (score_ != 0D) {
          output.writeDouble(202, score_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (cid_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
                  .computeUInt64Size(201, cid_);
        }
        if (score_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
                  .computeDoubleSize(202, score_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj instanceof com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta)) {
          return super.equals(obj);
        }
        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta other = (com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta) obj;

        boolean result = true;
        result = result && (getCid()
                == other.getCid());
        result = result && (
                java.lang.Double.doubleToLongBits(getScore())
                        == java.lang.Double.doubleToLongBits(
                        other.getScore()));
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getCid());
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getScore()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
      }
      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommentHotFlowVector.CommentHotflowMeta}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
              // @@protoc_insertion_point(builder_implements:CommentHotFlowVector.CommentHotflowMeta)
              com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_CommentHotflowMeta_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.class, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder.class);
        }

        // Construct using com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          cid_ = 0L;

          score_ = 0D;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor;
        }

        public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getDefaultInstanceForType() {
          return com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.getDefaultInstance();
        }

        public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta build() {
          com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta buildPartial() {
          com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta result = new com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta(this);
          result.cid_ = cid_;
          result.score_ = score_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta) {
            return mergeFrom((com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta other) {
          if (other == com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.getDefaultInstance()) return this;
          if (other.getCid() != 0L) {
            setCid(other.getCid());
          }
          if (other.getScore() != 0D) {
            setScore(other.getScore());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long cid_ ;
        /**
         * <code>uint64 cid = 201;</code>
         */
        public long getCid() {
          return cid_;
        }
        /**
         * <code>uint64 cid = 201;</code>
         */
        public Builder setCid(long value) {

          cid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 cid = 201;</code>
         */
        public Builder clearCid() {

          cid_ = 0L;
          onChanged();
          return this;
        }

        private double score_ ;
        /**
         * <code>double score = 202;</code>
         */
        public double getScore() {
          return score_;
        }
        /**
         * <code>double score = 202;</code>
         */
        public Builder setScore(double value) {

          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double score = 202;</code>
         */
        public Builder clearScore() {

          score_ = 0D;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:CommentHotFlowVector.CommentHotflowMeta)
      }

      // @@protoc_insertion_point(class_scope:CommentHotFlowVector.CommentHotflowMeta)
      private static final com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta();
      }

      public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CommentHotflowMeta>
              PARSER = new com.google.protobuf.AbstractParser<CommentHotflowMeta>() {
        public CommentHotflowMeta parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommentHotflowMeta(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CommentHotflowMeta> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CommentHotflowMeta> getParserForType() {
        return PARSER;
      }

      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int VECTOR_FIELD_NUMBER = 211;
    private java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta> vector_;
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    public java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta> getVectorList() {
      return vector_;
    }
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    public java.util.List<? extends com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder>
    getVectorOrBuilderList() {
      return vector_;
    }
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    public int getVectorCount() {
      return vector_.size();
    }
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getVector(int index) {
      return vector_.get(index);
    }
    /**
     * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
     */
    public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder getVectorOrBuilder(
            int index) {
      return vector_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      for (int i = 0; i < vector_.size(); i++) {
        output.writeMessage(211, vector_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vector_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(211, vector_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector)) {
        return super.equals(obj);
      }
      com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector other = (com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector) obj;

      boolean result = true;
      result = result && getVectorList()
              .equals(other.getVectorList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getVectorCount() > 0) {
        hash = (37 * hash) + VECTOR_FIELD_NUMBER;
        hash = (53 * hash) + getVectorList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommentHotFlowVector}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:CommentHotFlowVector)
            com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.class, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.Builder.class);
      }

      // Construct using com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVectorFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (vectorBuilder_ == null) {
          vector_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          vectorBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.internal_static_CommentHotFlowVector_descriptor;
      }

      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector getDefaultInstanceForType() {
        return com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.getDefaultInstance();
      }

      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector build() {
        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector buildPartial() {
        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector result = new com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector(this);
        int from_bitField0_ = bitField0_;
        if (vectorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vector_ = java.util.Collections.unmodifiableList(vector_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vector_ = vector_;
        } else {
          result.vector_ = vectorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector) {
          return mergeFrom((com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector other) {
        if (other == com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.getDefaultInstance()) return this;
        if (vectorBuilder_ == null) {
          if (!other.vector_.isEmpty()) {
            if (vector_.isEmpty()) {
              vector_ = other.vector_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVectorIsMutable();
              vector_.addAll(other.vector_);
            }
            onChanged();
          }
        } else {
          if (!other.vector_.isEmpty()) {
            if (vectorBuilder_.isEmpty()) {
              vectorBuilder_.dispose();
              vectorBuilder_ = null;
              vector_ = other.vector_;
              bitField0_ = (bitField0_ & ~0x00000001);
              vectorBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getVectorFieldBuilder() : null;
            } else {
              vectorBuilder_.addAllMessages(other.vector_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta> vector_ =
              java.util.Collections.emptyList();
      private void ensureVectorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vector_ = new java.util.ArrayList<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta>(vector_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder> vectorBuilder_;

      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta> getVectorList() {
        if (vectorBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vector_);
        } else {
          return vectorBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public int getVectorCount() {
        if (vectorBuilder_ == null) {
          return vector_.size();
        } else {
          return vectorBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta getVector(int index) {
        if (vectorBuilder_ == null) {
          return vector_.get(index);
        } else {
          return vectorBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder setVector(
              int index, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta value) {
        if (vectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorIsMutable();
          vector_.set(index, value);
          onChanged();
        } else {
          vectorBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder setVector(
              int index, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder builderForValue) {
        if (vectorBuilder_ == null) {
          ensureVectorIsMutable();
          vector_.set(index, builderForValue.build());
          onChanged();
        } else {
          vectorBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder addVector(com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta value) {
        if (vectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorIsMutable();
          vector_.add(value);
          onChanged();
        } else {
          vectorBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder addVector(
              int index, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta value) {
        if (vectorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVectorIsMutable();
          vector_.add(index, value);
          onChanged();
        } else {
          vectorBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder addVector(
              com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder builderForValue) {
        if (vectorBuilder_ == null) {
          ensureVectorIsMutable();
          vector_.add(builderForValue.build());
          onChanged();
        } else {
          vectorBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder addVector(
              int index, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder builderForValue) {
        if (vectorBuilder_ == null) {
          ensureVectorIsMutable();
          vector_.add(index, builderForValue.build());
          onChanged();
        } else {
          vectorBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder addAllVector(
              java.lang.Iterable<? extends com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta> values) {
        if (vectorBuilder_ == null) {
          ensureVectorIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, vector_);
          onChanged();
        } else {
          vectorBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder clearVector() {
        if (vectorBuilder_ == null) {
          vector_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          vectorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public Builder removeVector(int index) {
        if (vectorBuilder_ == null) {
          ensureVectorIsMutable();
          vector_.remove(index);
          onChanged();
        } else {
          vectorBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder getVectorBuilder(
              int index) {
        return getVectorFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder getVectorOrBuilder(
              int index) {
        if (vectorBuilder_ == null) {
          return vector_.get(index);  } else {
          return vectorBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public java.util.List<? extends com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder>
      getVectorOrBuilderList() {
        if (vectorBuilder_ != null) {
          return vectorBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vector_);
        }
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder addVectorBuilder() {
        return getVectorFieldBuilder().addBuilder(
                com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.getDefaultInstance());
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder addVectorBuilder(
              int index) {
        return getVectorFieldBuilder().addBuilder(
                index, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.getDefaultInstance());
      }
      /**
       * <code>repeated .CommentHotFlowVector.CommentHotflowMeta vector = 211 [packed = false];</code>
       */
      public java.util.List<com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder>
      getVectorBuilderList() {
        return getVectorFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder>
      getVectorFieldBuilder() {
        if (vectorBuilder_ == null) {
          vectorBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMeta.Builder, com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector.CommentHotflowMetaOrBuilder>(
                  vector_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vector_ = null;
        }
        return vectorBuilder_;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CommentHotFlowVector)
    }

    // @@protoc_insertion_point(class_scope:CommentHotFlowVector)
    private static final com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector();
    }

    public static com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommentHotFlowVector>
            PARSER = new com.google.protobuf.AbstractParser<CommentHotFlowVector>() {
      public CommentHotFlowVector parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommentHotFlowVector(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommentHotFlowVector> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommentHotFlowVector> getParserForType() {
      return PARSER;
    }

    public com.weibo.api.api_test.CommentHotFlowVectorWrap.CommentHotFlowVector getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_CommentHotFlowVector_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_CommentHotFlowVector_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_CommentHotFlowVector_CommentHotflowMeta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\024AttitudeByMePb.proto\"\211\001\n\024CommentHotFlo" +
                    "wVector\022=\n\006vector\030\323\001 \003(\0132(.CommentHotFlo" +
                    "wVector.CommentHotflowMetaB\002\020\000\0322\n\022Commen" +
                    "tHotflowMeta\022\014\n\003cid\030\311\001 \001(\004\022\016\n\005score\030\312\001 \001" +
                    "(\001B2\n\026com.weibo.api.api_testB\030CommentHot" +
                    "FlowVectorWrapb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_CommentHotFlowVector_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_CommentHotFlowVector_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_CommentHotFlowVector_descriptor,
            new java.lang.String[] { "Vector", });
    internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor =
            internal_static_CommentHotFlowVector_descriptor.getNestedTypes().get(0);
    internal_static_CommentHotFlowVector_CommentHotflowMeta_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_CommentHotFlowVector_CommentHotflowMeta_descriptor,
            new java.lang.String[] { "Cid", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
